### ISSUE TITLE
MR script status link incorrect

### ISSUE THREAD

**Issue by RezaSeedin** [burkybang/NetSuite-Advanced-Feedback#10]
**Describe the bug**
When clicking on the status link on a MR script it goes to the SS status page

**To Reproduce**
Go to SS and hit status VS go to MR and hit status
https://XXXXapp.netsuite.com/app/common/scripting/scriptstatus.nl?sortcol
https://XXXXXX.app.netsuite.com/app/common/scripting/mapreducescriptstatus.nl?sortcol=dcreated&sortdir=DESC&date=TODAY&datefrom=13%2F12%2F2021&dateto=13%2F12%2F2021&scripttype=1231&primarykey=10098

Note that in the MR deployment it does point to the correct status page just the script page has the incorrect link

**Comment by burkybang** [comment]
Thanks! The fix will be in the next release.
