### ISSUE TITLE
Display Issue

### ISSUE THREAD

**Issue by sbuttitta** [burkybang/NetSuite-Advanced-Feedback#12]
**Describe the bug**
On setup manager -> Nexuses screen, the filters and export icons overwrite each other.

**To Reproduce**
1. Go to https://5864486.app.netsuite.com/app/setup/mainsetup.nl?sc=-10

**Expected behavior**
Not overwriting

**Screenshots**
![image](https://user-images.githubusercontent.com/41705848/147584322-7b117a0f-93a4-49ea-9bea-54f77be0a87b.png)

**Additional context**

**Comment by burkybang** [comment]
Thanks! The fix will be in the next release.
