### ISSUE TITLE
Height of sublists in SCA Configuration

### ISSUE THREAD

**Issue by RandomHarlz** [burkybang/NetSuite-Advanced-Feedback#2]
**Describe the bug**
In the SCA Configuration when on a subtab with a sublist the height of the containing div (`.uir-machine-table-container`) is set to `calc(100vh - 300px) !important`, which is pushing any sublists below it almost a whole page length down. 
Then the `.nltabcontent` div around that appears to have jQuery calculating it's height a further page length, which results in a whole lot more whitespace than needed.

**To Reproduce**
1. Go to Setup > SuiteCommerce Advanced > Configuration
2. Click on Layout > Light Colors
3. Scroll down
4. See masses of whitespace
5. Click on Search > Result Display Options
6. Repeat setps 3 & 4

**Expected behavior**
This amount of whitespace is almost unethical 😝 
But, mainly it really annoying when multiple sublists are on the one page cos I have to scroll so far between them.

**Screenshots**
![image](https://user-images.githubusercontent.com/9343418/53314182-21742d80-3911-11e9-992f-7ab8f34a50d2.png)

**Comment by burkybang** [comment]
I fixed this. It will be pushed in the next update.

**Comment by burkybang** [comment]
I just pushed the fix in v17.5.
