### ISSUE TITLE
NetSuite Error/Warning/Success Messages can't be closed when page is scrolled

### ISSUE THREAD

**Issue by RandomHarlz** [burkybang/NetSuite-Advanced-Feedback#3]
**Describe the bug**
Can't close NetSuite popup messages when page is scrolled.

**To Reproduce**
1. On any page that has an error or warning message popup
2. Scroll down so that header is floating (you can see a shadow)
3. Attempt to close popup by clicking 'X'
4. Scroll to top, when header is fixed to top (no shadow)
5. Close popup by clicking 'X'

**Expected behavior**
Should be able to close popup anywhere on the page, even when scrolled.

**Screenshots**
![image](https://user-images.githubusercontent.com/9343418/53467570-e60d6680-3aaa-11e9-9bb6-aba5163779cf.png)

**Comment by burkybang** [comment]
I fixed this. It will be pushed in the next update.

**Comment by burkybang** [comment]
I just pushed the fix in v17.5.
