### ISSUE TITLE
Code Snippet adds 'undefined' in HTML when not there

### ISSUE THREAD

**Issue by RandomHarlz** [burkybang/NetSuite-Advanced-Feedback#5]
**Describe the bug**
When viewing a page with HTML in a text area that has been converted to a code snippet the word `undefined` is being added in the HTML.

**To Reproduce**
1. This was done on a Commerce Category, but I presume it would work on any text area
2. Edit the text area and add the following HTML: `<p>Restoration Online offers a fantastic range of bathroom and kitchen sinks. These include bathroom pedestal basins as well as the full selection of 1901 Sinks including Belfast sinks and butler sinks. Our fireclay sinks are available in both drop-in and under-mount style and in a good range of different sizes. You are guaranteed to find the perfect sink for your needs. Our kitchen sinks are perfectly complimented by our range of <a title="1901 Kitchen Taps" href="/taps/kitchen-taps/bridging-set-taps?brand=1901-Sinks--AND--Taps">Australian-made 1901 Kitchen Taps</a>.</p>`
3. Save the record
4. View the record and notice that in between the `title`/`href` and the `=` the word `undefined` has been added.

**Expected behavior**
The `undefined` text shouldn't be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/9343418/57272662-f871d500-70d7-11e9-9b0e-6dacd9344975.png)

**Additional context**
🙂

**Comment by burkybang** [comment]
Fixed in version 19.1.2
