### ISSUE TITLE
Live View only works with cursor above list

### ISSUE THREAD

**Issue by RandomHarlz** [burkybang/NetSuite-Advanced-Feedback#7]
**Describe the bug**
The 'Live View' checkbox only seems to work on a number of pages (not all), when the cursor is positioned at the top of the page above the list. If the cursor moves down the page below the header information and onto the list, the 'Live View' checkbox greys out and doesn't refresh the list. 

**To Reproduce**
1. Go to Customisation > SuiteBundler > Search & Install Bundles > List
2. Click on 'Live View' and leave cursor next to button
3. Note that that page refreshes
4. Move cursor below list header
5. Note that the 'Live View' button greys out and the refresh does not happen

**Expected behavior**
I would expect the list to refresh no matter where the cursor was. It seems strange to me that it would only work at the top of the page.

**Screenshots**
Greyed out Live View button:
![image](https://user-images.githubusercontent.com/9343418/64754767-047d1000-d56c-11e9-9b53-b334469701de.png)

**Additional context**
I miss you! 😍 When are you coming to Melbourne next?

**Comment by burkybang** [comment]
@RandomHarlz That's a feature 🙂
