### ISSUE TITLE
Field ID Prefix

### ISSUE THREAD

**Issue by swartzlib7** [burkybang/NetSuite-Advanced-Feedback#8]
Would be great to have a configuration value for a custom field id prefix value such as "_scs" or simular followed by the value as it auto inserts right now... Currently I have to type the prefix in the field label, lock the id field and then remove the value from the label.

**Comment by burkybang** [comment]
Nice idea! That's definitely doable.

**Comment by burkybang** [comment]
😃 
![image](https://user-images.githubusercontent.com/927886/81849489-963a8400-9524-11ea-94c2-042755b9ed26.png)

**Comment by burkybang** [comment]
This will be in version 21.2.0

**Comment by swartzlib7** [comment]
Love this, thanks for adding it so fast!
